Convert VContentLink story to MDX
WordPress/openverse pull request #1062
Opened 2023-03-29 12:22 UTC by sepehrrezaei

## Fixes

Related to #584 by @dhruvkb 

## Description

This PR updates the story of VContentLink to use the composition API (MDX). Here is the screenshot of the converted VContentLink to MDX in the storybook: 
<img width="1606" alt="Screenshot 2023-03-29 at 14 14 23" src="https://user-images.githubusercontent.com/54465154/228532135-e199dbe5-6a1e-4313-8be2-11ca288f8050.png">

## Testing Instructions

Run the Storybook from this PR to see that VContentLink is working properly in the storybook.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-04-03 04:24 UTC, obulat requested changes
The stories are great!

One change request here is to replace all instances of `VContentList` with `VContentLink`.

2023-04-03 04:24 UTC, obulat commented on frontend/src/components/VContentLink/meta/VContentLink.stories.mdx
> +
```suggestion
# VContentLink

```

The <h1> was missing in this story.

2023-04-03 14:18 UTC, sepehrrezaei commented on frontend/src/components/VContentLink/meta/VContentLink.stories.mdx
> +
Sure, Thanks

2023-04-11 11:34 UTC, dhruvkb requested changes
This is really good! Thank you @sepehrrezaei. I do have some minor suggestions though.

2023-04-11 11:34 UTC, dhruvkb commented on frontend/src/components/VContentLink/meta/VContentLink.stories.mdx
> +## Default VContentLink
Nit: `VContentLink` is implied here.

```suggestion
## Default
```

2023-04-11 11:34 UTC, dhruvkb commented on frontend/src/components/VContentLink/meta/VContentLink.stories.mdx
> +
Optional for this PR: a little description about each variant would be nice.

2023-04-11 11:34 UTC, dhruvkb commented on frontend/src/components/VContentLink/meta/VContentLink.stories.mdx
> +
Please include a note that this story should be viewed in the Canvas tab. I was a bit confused when the "mobile" story was same as the desktop one when seen in the Docs tab.

2023-04-13 14:52 UTC, dhruvkb approved these changes
Approving, shelving the recommended changes for future improvements.

2023-04-13 14:52 UTC, merged