Analytics event: SELECT_EXTERNAL_SOURCE event
WordPress/openverse pull request #1158
Opened 2023-04-10 10:30 UTC by obulat

## Fixes

Fixes #1076 by @dhruvkb

## Description

This PR adds `SELECT_EXTERNAL_SOURCE` event that is triggered when the user clicks on one of the `external source` buttons inside the External sources popover/modal below the search results or on one of the buttons on the "No results" page.
The buttons are also updated to use the new variants and sizes.

## Testing Instructions

Run analytics and the frontend dev server. Click on one of the external sources below the search results or search for "nonexistentquery" and click on one of the buttons on the "No results" page.
You should see the event in Plausible.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-04-12 10:28 UTC, dhruvkb reviewed
I think we should also include which part of the UI the external source was selected from in something like a `uiComponent` param.

2023-04-12 20:17 UTC, zackkrida commented
@obulat @dhruvkb regarding tracking which part of the UI is calling the event, I have a related `useComponentName` composable in one of my event PRs that might be useful:

https://github.com/WordPress/openverse/blob/add/events-change-content-type/frontend/src/composables/use-component-name.ts

2023-04-25 03:46 UTC, obulat commented on frontend/src/components/VHeader/VHeaderMobile/VContentSettingsButton.vue
> +import VSearchBarButton from "../../../components/VHeader/VHeaderMobile/VSearchBarButton.vue"
```suggestion
import VSearchBarButton from "~/components/VHeader/VHeaderMobile/VSearchBarButton.vue"
```

2023-05-02 15:55 UTC, zackkrida approved these changes
Perfect! LGTM.

2023-05-03 00:06 UTC, sarayourfriend requested changes
I don't understand the goal behind the `url` property (ambiguous name aside). Here are my two testing examples:

![image](https://user-images.githubusercontent.com/24264157/235810042-48cc61b3-1fcb-4c34-9696-10c67fc2e7ee.png)

Stored in this way, I don't know what we'll be able to use these for. For one, it isn't easy to query any information against this field that isn't _easier_ elsewhere (specifically query and name). On top of that, it effectively duplicates the name and the query.

My question boils down to: what is the goal for the `url` payload data that isn't covered by the other payload items?

2023-05-03 04:04 UTC, dhruvkb approved these changes
Agree with changes suggested by Sara. Everything else LGTM.

2023-05-03 06:41 UTC, obulat commented on frontend/src/types/analytics.ts
> +    url: string
I removed the `url` entirely, as it does not provide much useful non-duplicated information.

2023-05-03 06:41 UTC, obulat commented on frontend/test/playwright/e2e/external-sources.spec.ts
> +  })
Issue created: https://github.com/WordPress/openverse/issues/1992

2023-05-03 06:42 UTC, merged