Remove @types/lodash.sortBy from project
WordPress/openverse pull request #1937
Opened 2023-04-30 18:49 UTC by wasimTQ

## Fixes

Fixes #1930 by @sarayourfriend 

## Description

This PR removes `@types/lodash.sortBy`. 

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-04-30 23:08 UTC, sarayourfriend commented
Thanks for the contribution, @wasimTQ, and welcome to Openverse! To complete this PR, you'll need to update `pnpm-lock.yaml` as well. To do so, run `pnpm install` locally in this branch and commit the changes to `pnpm-lock.yaml`.

2023-05-01 08:34 UTC, wasimTQ commented
> Thanks for the contribution, @wasimTQ, and welcome to Openverse! To complete this PR, you'll need to update `pnpm-lock.yaml` as well. To do so, run `pnpm install` locally in this branch and commit the changes to `pnpm-lock.yaml`.

Got it. I was wondering why it's failing

2023-05-01 08:58 UTC, wasimTQ commented
@obulat @sarayourfriend When I ran the precommit locally, it worked. I don't know why it's failing on PR.

Should I remove the type and use it as default export as it mentioned?

2023-05-01 09:23 UTC, obulat requested changes
The lock file should not contain so many changes. The pnpm version mismatch might have caused this, but I'm not entirely sure.

2023-05-01 09:23 UTC, obulat commented on pnpm-lock.yaml
The lock file appears to have changes for a lot of unrelated packages, which causes failures in the linting.
When I removed `@types/lodash.sortby` locally, and ran `just node-install, I only saw 4 changes in `pnpm-lock.yaml` file. Could you check the version of `pnpm` you are using? It should match the version in `package.json`'s engines property to generate the correct lock file.

2023-05-01 10:05 UTC, wasimTQ commented on pnpm-lock.yaml
But it passes on local. Let me try after correcting the version

2023-05-01 10:21 UTC, wasimTQ commented on pnpm-lock.yaml
Can you confirm it once the pipeline finish?

2023-05-01 11:59 UTC, obulat approved these changes

2023-05-01 11:59 UTC, obulat commented
All the checks are 🟢 now! Thank you for your contribution, @wasimTQ 🎉

2023-05-01 23:23 UTC, sarayourfriend approved these changes

2023-05-01 23:23 UTC, merged