Narrow filters for emitting new docs
WordPress/openverse pull request #1983
Opened 2023-05-02 22:04 UTC by veronewra

## Fixes

Fixes #[issue number] by @[issue author]

## Description

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-05-02 22:16 UTC, veronewra commented
sorry this is my first time contributing to openverse- it looks like it failed some checks. I would love some feedback and guidance

2023-05-03 01:42 UTC, AetherUnbound commented
Thanks and congrats on your first contribution @veronewra! Those are checks that maintainers need to address regarding proper labeling of the PR - I've gone ahead and fixed them 😄

2023-05-03 01:50 UTC, AetherUnbound commented
@dhruvkb is this the set of changes you were imagining when describing #1932?

2023-05-03 04:22 UTC, dhruvkb requested changes
Before a more thorough review, the `frontend` filters should not change, only the fillets for `documentation`.

2023-05-03 05:01 UTC, obulat submitted a review, later dismissed
Welcome to Openverse, @veronewra! 😺 

Could you re-add the frontend parts (lines 13-21)?

Also, I think we should add these after line 18, because it can also change the documentation:
`frontend/src/styles/tailwind.css`

2023-05-03 05:19 UTC, obulat commented on .github/filters.yml
>    - .github/workflows/ci_cd.yml
```suggestion
  - .github/workflows/ci_cd.yml
  frontend:
  - frontend/**
  - package.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - .npmrc
  - .pnpmfile.cjs
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
```

2023-05-03 05:19 UTC, obulat commented on .github/filters.yml
> +  - frontend/tailwind.config.js
```suggestion
  - frontend/tailwind.config.js
  - frontend/src/styles/tailwind.css
```

2023-05-03 07:37 UTC, dhruvkb commented
#1933 might be a blocker/conflict-creator for this PR. Just noting.

2023-05-03 16:48 UTC, dhruvkb requested changes
You will also need to update the CI + CD workflow.
<img width="957" alt="image" src="https://user-images.githubusercontent.com/16580576/235984332-de918746-0de1-4339-816d-4c3e24ae0bea.png">

2023-05-03 16:48 UTC, dhruvkb commented on .github/filters.yml
> +  - frontend/.storybook
I don't think `filters.yml` works with directories.
```suggestion
  - frontend/.storybook/**
```

2023-05-03 16:48 UTC, dhruvkb commented on .github/filters.yml
>    - .github/workflows/ci_cd.yml
Drop these lines w.r.t. #1933

```suggestion
  # Change to the CI + CD workflow should trigger complete workflow.
  - .github/workflows/ci_cd.yml
```

2023-05-04 19:52 UTC, veronewra commented
Right! Should I remove all instances of "needs.get-changes.outputs.frontend == 'true' " in the ci_cd.yml file?

2023-05-05 04:42 UTC, dhruvkb commented
Not all @veronewra, these 2 specifically:

https://github.com/WordPress/openverse/blob/e78b0bc8c1a0b4438912b7843973bbfeb5c877e6/.github/workflows/ci_cd.yml#L702

https://github.com/WordPress/openverse/blob/e78b0bc8c1a0b4438912b7843973bbfeb5c877e6/.github/workflows/ci_cd.yml#L921

2023-05-06 09:17 UTC, dhruvkb approved these changes
Awesome, LGTM! Thanks for this contribution @veronewra.

2023-05-08 14:24 UTC, zackkrida approved these changes

2023-05-08 14:29 UTC, merged

2023-05-08 22:41 UTC, veronewra commented
@dhruvkb @AetherUnbound I want to join the slack so I can ask questions /attend office hours, but when I try to make a wordpress account it does not send me a confirmation email (I checked spam and all). Is there a way I can directly join the slack? Thanks:)

2023-05-09 14:14 UTC, AetherUnbound commented
@veronewra we'd love to have you! It's a little complex to get added, check https://make.wordpress.org/chat/ for instructions (you'll need to be logged into a WordPress.org account first). Here's the instructions I see when I'm logged in:
![Screenshot_20230509-071306.png](https://github.com/WordPress/openverse/assets/10214785/a954db92-5113-4bfd-b7a2-955dbe73fa7e)