removed navigation store's embedded property #2159
WordPress/openverse pull request #2212
Opened 2023-05-28 17:37 UTC by YashGaur000

## Fixes

Fixes #2159 by @obulat 

## Description
The code checks if the query parameter "embedded" exists and has a value of "true". If it does, it sets the "isEmbedded" property in the "navigation store" to true. But we needed to remove this code snippets,

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-05-29 11:38 UTC, obulat commented on frontend/src/middleware/middleware.ts
>    if (process.client) {
```suggestion
  if (process.client) {
```
Could you also remove the `sendWindowMessage`?

2023-05-29 11:41 UTC, obulat requested changes
This is a great start, @YashGaur000!

Could you also remove the `sendWindowMessage` call from lines 36-41 in the updated `middleware` file, and the `isEmbedded` property and methods that update it from the `navigation` store: `frontend/src/stores/navigation.ts` ?

2023-05-29 12:08 UTC, obulat requested changes
To finish fixing, we need to also remove:
- import on line 1
- `route` param on line 29
- `if(process.client)` statement on lines 36-37

2023-05-29 12:31 UTC, obulat requested changes
We can also delete `frontend/src/plugins/url-change.ts`. After that, we would need to delete it from the `plugins` array in `nuxt.config.ts`

2023-05-29 13:09 UTC, YashGaur000 commented
Why is there a need to delete it? Can you help me with this, I'm new to open source.

2023-05-30 05:54 UTC, obulat commented
> Deleted frontend/src/plugins/url-change.ts and from the plugins array in nuxt.config.ts also.
> 
> *Why is there a need to delete it? Can you help me with this, I'm kinda new to open source.

Sure, @YashGaur000! I'm sorry I didn't give more details in the issue. The `isEmbedded` property is used in several places, and you've removed it from them. Previously, Openverse was hosted inside the wordpress.org iframe. Now, the old URL (https://wordpress.org/openverse) is only used for redirect to the new domain, `https://openverse.org`

`frontend/src/plugins/url-change.ts` is the file that was used to sync the URL between the iframe and the Openverse app. It is not needed anymore.

I've removed the unused tests, and now this PR is ready 🚀 Thank you for your contribution, and welcome to Openverse!

2023-05-30 05:54 UTC, obulat approved these changes

2023-05-30 12:46 UTC, YashGaur000 commented
Thank you for your guidance and for making me understand the these issue needed to be altered. And Thank you for welcoming me in openverse.

2023-05-30 12:48 UTC, YashGaur000 commented
Can you please tell me why this other review is pending? And will it even be reviewed?

2023-05-30 12:56 UTC, YashGaur000 commented
Thank you so much to approve this pull request @obulat. Can I know when
this pull request be merged? And how do I become the contributor in
openverse?

On Tue, May 30, 2023 at 11:25 AM Olga Bulat ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WordPress/openverse/pull/2212#pullrequestreview-1450117733>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYYJGB6POEVFG4ZDCARAUDLXIWDTTANCNFSM6AAAAAAYR7EYRA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-30 13:57 UTC, obulat commented
> Can I know when this pull request be merged?

Our policy is that every PR needs 2 approvals to be merged, @YashGaur000.

2023-05-30 14:12 UTC, YashGaur000 commented
When will the other one review it? Will she even review it?

On Tue, 30 May, 2023, 19:28 Olga Bulat, ***@***.***> wrote:

> Can I know when this pull request be merged?
>
> Our policy is that every PR needs 2 approvals to be merged, @YashGaur000
> <https://github.com/YashGaur000>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WordPress/openverse/pull/2212#issuecomment-1568484615>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYYJGB5GITMHDV4U6WBA6RLXIX4GVANCNFSM6AAAAAAYR7EYRA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-02 04:25 UTC, dhruvkb approved these changes
LGTM, thanks for the contribution @YashGaur000! Please also note that you're free to work on another issue while a PR is awaiting a second approval.

2023-06-02 04:27 UTC, YashGaur000 commented
Okay. Thank you to inform me. I appreciate that a lot.

On Fri, 2 Jun, 2023, 09:55 Dhruv Bhanushali, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> LGTM, thanks for the contribution @YashGaur000
> <https://github.com/YashGaur000>! Please also note that you're free to
> work on another issue while a PR is awaiting a second approval.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WordPress/openverse/pull/2212#pullrequestreview-1456628264>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYYJGB7OELQIJCZQCZ3247DXJFTMXANCNFSM6AAAAAAYR7EYRA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-02 04:34 UTC, merged