Add OPEN_PAGES_MENU event
WordPress/openverse pull request #2398
Opened 2023-06-14 01:22 UTC by zackkrida

## Fixes

Fixes #1077 by @dhruvkb 

## Description

Adds an analytics event for the opening of the pages menu. This is a quite simple one to implement.

While trying to push this I also noticed that after the merging of #2271, some of the generated translation files fail eslint:

```shell
openverse/frontend/src/locales/de.json
  171:29  error  Irregular whitespace not allowed  no-irregular-whitespace
  236:29  error  Irregular whitespace not allowed  no-irregular-whitespace
  472:29  error  Irregular whitespace not allowed  no-irregular-whitespace
  706:29  error  Irregular whitespace not allowed  no-irregular-whitespace

openverse/frontend/src/locales/fr.json
   68:28   error  Irregular whitespace not allowed  no-irregular-whitespace
   68:108  error  Irregular whitespace not allowed  no-irregular-whitespace
   68:112  error  Irregular whitespace not allowed  no-irregular-whitespace
   68:135  error  Irregular whitespace not allowed  no-irregular-whitespace
   68:143  error  Irregular whitespace not allowed  no-irregular-whitespace
   68:148  error  Irregular whitespace not allowed  no-irregular-whitespace
   68:156  error  Irregular whitespace not allowed  no-irregular-whitespace
   68:161  error  Irregular whitespace not allowed  no-irregular-whitespace
   68:173  error  Irregular whitespace not allowed  no-irregular-whitespace
   71:32   error  Irregular whitespace not allowed  no-irregular-whitespace
   92:39   error  Irregular whitespace not allowed  no-irregular-whitespace
  182:48   error  Irregular whitespace not allowed  no-irregular-whitespace
  182:56   error  Irregular whitespace not allowed  no-irregular-whitespace

openverse/frontend/src/locales/lv.json
  11:24  error  Irregular whitespace not allowed  no-irregular-whitespace

openverse/frontend/src/locales/ru.json
  321:230  error  Irregular whitespace not allowed  no-irregular-whitespace
```

I don't think we want to lint those files at all, so I've added them to the root .eslintignore. Does that seem right @obulat?

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-06-17 12:13 UTC, obulat commented
@zackkrida, because of this issue I learned that some languages use NBSP (non-breaking space) between words and punctuation marks (more context in GlotPress: https://github.com/GlotPress/GlotPress/issues/801). Since `json` locale files are gitignored anyways, it seems appropriate to ignore them from linting, too.

2023-06-17 12:20 UTC, obulat requested changes
This change is working well.
The blocker here is the eslintignore change. And it would be really nice to add a unit test.

2023-06-17 12:20 UTC, obulat commented on .eslintignore
> +frontend/src/locales
```suggestion
frontend/src/locales/*.json
```
There are some js files in the locales folder that _should_ be linted.

2023-06-17 12:20 UTC, obulat commented on frontend/src/components/VHeader/VHeaderInternal.vue
> +    const eventedOnTriggerClick = (...args) => {
`onTriggerClick` does not take any arguments. I don't think we need `...args` here.

2023-06-18 14:59 UTC, zackkrida commented
Drafting while I add a unit test.

2023-06-19 16:57 UTC, zackkrida commented
@obulat and @dhruvkb this is ready for review. I've added a test spec for the internal header with a unit test for this event.

2023-06-19 17:31 UTC, obulat approved these changes
Perfect! Works well both on the homepage and on the content pages. And **more** tests 🎉

2023-06-28 14:17 UTC, merged