Fix/media error handling
WordPress/openverse pull request #2618
Opened 2023-07-11 18:13 UTC by obulat

## Fixes

Fixes #2588 by @obulat

## Description

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-07-21 05:05 UTC, AetherUnbound approved these changes
These changes generally make sense to me! I followed the testing instructions and everything worked as expected.

2023-07-24 02:01 UTC, dhruvkb requested changes
LGTM, works well!

> In the `media` store, we set `fetchingError` to 404 status in case there are no results, to show the 404 page.

This seems wrong to me. If we have no results for a query, that does not imply 404 because the `/search` page itself still exists.

2023-07-25 05:27 UTC, obulat commented on frontend/src/pages/search.vue
> +      Boolean(supported.value && !resultCount.value && searchTerm.value !== "")
We trim the `searchTerm` value when we set it in the store, so we don't need to do it here.

2023-07-25 05:36 UTC, obulat commented
> This seems wrong to me. If we have no results for a query, that does not imply 404 because the /search page itself still exists.
Right, I haven't thought about it. Thank you, Dhruv!

2023-07-26 14:15 UTC, obulat commented
> LGTM, works well!
> 
> > In the `media` store, we set `fetchingError` to 404 status in case there are no results, to show the 404 page.
> 
> This seems wrong to me. If we have no results for a query, that does not imply 404 because the `/search` page itself still exists.

I updated the PR to set the error to `{message: NO_RESULTS}` when we have no results so that we show the client-side No results page instead of the Nuxt yellow error page.

2023-07-28 06:05 UTC, dhruvkb approved these changes
LGTM, thanks! I appreciate your quick turnaround on the requested changes.

2023-07-28 06:07 UTC, merged