Update frontend/src/components/VSkeleton/VGridSkeleton.vue
WordPress/openverse pull request #2636
Opened 2023-07-12 07:29 UTC by viktoriussuwandi

Fixes #[2440](https://github.com/WordPress/openverse/issues/2440) by @obulat

## Description
Hi [obulat](https://github.com/obulat),
just trying to help on this issue, please check it out

[Update frontend/src/components/VSkeleton/VGridSkeleton.vue](https://github.com/WordPress/openverse/commit/e3a9743be94d5a61129617ba080defcd1b0f4788)

## Testing Instructions

## Checklist

- [X] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [X] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added or updated tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no visible errors.
- [X] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-07-12 12:21 UTC, obulat requested changes
The tailwind classes need to have `@apply` to work inside the Vue component `<style>`.

2023-07-12 12:21 UTC, obulat commented on frontend/src/components/VSkeleton/VGridSkeleton.vue
> +  aspect-square;
```suggestion
  @apply aspect-square;
```

2023-07-12 12:22 UTC, obulat commented on frontend/src/components/VSkeleton/VGridSkeleton.vue
> +  gap-x-4;
```suggestion
  @apply columns-1 gap-x-4;
```

2023-07-12 14:32 UTC, obulat commented on frontend/src/components/VSkeleton/VGridSkeleton.vue
> +  .masonry {
```suggestion
```

We already set the column count to 3 in the `.masonry` declaration in line 70 (`md:columns-3`), so lines 72 and 73 should be deleted.

2023-07-12 17:33 UTC, obulat commented on frontend/src/components/VSkeleton/VGridSkeleton.vue
>      column-count: 3;
Line 72 also needs to be deleted.

2023-07-13 04:56 UTC, obulat requested changes
Sorry I haven't noticed the other style declarations below. You will also need to delete 
```
  @screen lg {
    column-count: 5;
}
```
The easiest and cleanest way would be to delete lines 71-76. This will remove extra blank lines, too.

2023-07-13 10:01 UTC, obulat approved these changes
There was one more extra bracket that was causing errors. I removed it, and now this PR is ready to go 🚀 
Thank you for your contribution, @viktoriussuwandi!

2023-07-14 00:54 UTC, AetherUnbound approved these changes
Changes LGTM! Thanks for your contribution!

2023-07-14 04:50 UTC, merged