add null check for images
WordPress/openverse pull request #2948
Opened 2023-09-01 05:50 UTC by akhilsrivatsa

## Fixes

Fixes #[issue number] by @[issue author]

## Description

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-09-01 05:56 UTC, akhilsrivatsa commented
Kinda new to this whole open source thing and its my first ever PR. Apologies if I screwed something up! @obulat @dhruvkb

2023-09-01 07:02 UTC, obulat commented
Hi @ akhilsrivatsa! Welcome to Openverse 🎉 

Which issue were you trying to address with this PR? I think the `null` check for images was already added, but if there is an open issue for that, could you please share it?
When you fill in the PR description, the `Fixes` section is really helpful because it links to the issue the PR solves. You can add the number of the issue and the issue author instead of the placeholder in brackets, and GitHub automatically adds the links. This is how it would look in the PR edit view:
```
Fixes #11111 by @obulat
```
If there is no issue, you can also find another one you can tackle by looking through the [issues tagged with `good first issue` label](https://github.com/WordPress/openverse/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). Please, feel free to ask for help whenever you need it.

2023-09-01 07:04 UTC, akhilsrivatsa commented
@obulat Here is the issue - #2923

2023-09-01 07:35 UTC, obulat requested changes
Thank you for linking to the issue!
I added a suggestion to make the check cleaner using the `?` operator (optional chaining), and approved the PR.
Note that you need 2 PR approvals to get it merged.

2023-09-01 07:35 UTC, obulat commented on frontend/src/components/VSearchResultsGrid/VImageGrid.vue
> +      v-if="images != null && !images.length && !fetchState.isFinished"
```suggestion
      v-if="!images?.length && !fetchState.isFinished"
```
Optional chaining operator `?`[^1] can make this expression cleaner. It returns `undefined` if `images` is null or undefined, and does not try to access the `.length` property.

[^1]: https://javascript.info/optional-chaining

2023-09-01 12:16 UTC, obulat approved these changes

2023-09-01 17:03 UTC, krysal commented
@obulat A test is failing after the modification on the strategy, I certainly find it strange for such a simple change! Could you take a second look on this?

2023-09-02 03:51 UTC, akhilsrivatsa commented
@obulat I just my checked github and I see that you've fixed it. Sorry for the delay.

2023-09-03 14:55 UTC, obulat commented
@akhilsrivatsa, it appears that the changes on main branch somehow affected the CI in your PR, and that caused a failure. I'm sorry for this confusion. I reverted my change that added an optional chaining, and now the PR is ✅  Thank you for your contribution!
@krysal, the PR is now ready for the second review. I think the testing failure was due to the changes on main, not changes in this PR.

2023-09-05 09:05 UTC, dhruvkb approved these changes
LGTM, except for a small nit.

2023-09-05 09:05 UTC, dhruvkb commented on frontend/src/components/VSearchResultsGrid/VImageGrid.vue
> +      v-if="images != null && !images.length && !fetchState.isFinished"
This also accounts for undefined.
```suggestion
      v-if="images && !images.length && !fetchState.isFinished"
```

2023-09-05 11:20 UTC, merged