Additional search views/add to store and api service
WordPress/openverse pull request #3140
Opened 2023-10-05 04:54 UTC by obulat

This PR is based on #3136, and will be undrafted after that PR is merged.

## Fixes

Fixes #2858 by @obulat

## Description

This PR updates the store and the media service to allow for getting collections (or additional search views).

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-11-28 12:42 UTC, obulat commented on frontend/src/components/VLoadMore.vue
> +
```suggestion
```

2023-11-28 12:43 UTC, obulat commented on frontend/src/components/VLoadMore.vue
> +import { useRoute, useRouter } from "@nuxtjs/composition-api"
```suggestion
import { useRoute } from "@nuxtjs/composition-api"
```

2023-11-30 16:22 UTC, fcoveram requested changes
It works great 👏 

I just noticed one area of improvement:
* When `VCollectionHeader` has a padding of 40px on the sides (`xs / sm / md`), top padding looks better with 8px.
* When `VCollectionHeader` has a padding of 24px on the sides (`lg / xl / 2xl`), top padding looks better with 0px.

On the other hand and something out of this scope, I noticed that loading these views keeps the page empty for a few milliseconds. It seems good idea showing the [media's skeleton](https://docs.openverse.org/storybook/?path=/story/components-skeleton--all-tab). Here is a video recording of what I see.

https://github.com/WordPress/openverse/assets/895819/bbb35dc6-2a85-4f28-aa0f-275d9cb8b40b

If you think is a good idea to include. I can request it in a new ticket.

2023-12-01 00:20 UTC, dhruvkb approved these changes
The pages work well, when they do work. I have nothing to add to @fcoveram's review, LGTM from my side!

2023-12-01 02:02 UTC, AetherUnbound reviewed
THIS IS SO COOOOOL! 🤩 It's amazing to see this come together on the frontend!! I have a few questions, but also - should we have any snapshots as part of this PR too?

2023-12-01 02:03 UTC, AetherUnbound approved these changes
I don't actually have anything additional that's blocking 😄

2023-12-01 12:35 UTC, obulat commented
> On the other hand and something out of this scope, I noticed that loading these views keeps the page empty for a few milliseconds. It seems good idea showing the [media's skeleton](https://docs.openverse.org/storybook/?path=/story/components-skeleton--all-tab). Here is a video recording of what I see.

I updated the paddings, @fcoveram . As for the loading skeletons: they were broken on `main` branch because a variable was renamed. I fixed the error on `main` and rebased this branch, so now you can see the loading skeletons when the media is loading.

2023-12-01 19:38 UTC, AetherUnbound commented on frontend/src/utils/validate-collection-params.ts
> +  firstParam: "tag" | "source"
Got it, hmm. I'm not sure I have a better term 😅 I think I also missed while looking at this that `creator` is the second part.

2023-12-01 22:51 UTC, fcoveram requested changes
I noticed one odd spacing in `VCollectionHeader` that can look better with the following two changes:
* Audio results of source, tag, and author in all breakpoints, margin-bottom looks better with `8px`. I refer to [this area](https://share.cleanshot.com/ZC2FXxlm).
* Image results of source, tag, and author in all breakpoints, margin-bottom looks better with `16px`. I refer to [this area](https://share.cleanshot.com/ZKY9kd3D).

Pardon the picky territory my suggestions belong to, but QA is the perfect stage for adjustments.

2023-12-02 11:02 UTC, obulat commented
> I noticed one odd spacing in `VCollectionHeader` that can look better with the following two changes:
> 
> * Audio results of source, tag, and author in all breakpoints, margin-bottom looks better with `8px`. I refer to [this area](https://share.cleanshot.com/ZC2FXxlm).
> * Image results of source, tag, and author in all breakpoints, margin-bottom looks better with `16px`. I refer to [this area](https://share.cleanshot.com/ZKY9kd3D).
> 
> Pardon the picky territory my suggestions belong to, but QA is the perfect stage for adjustments.

Thank you for re-reviewing! I've updated the paddings.

I also noticed that the collection pages really didn't render on the server at all, not just because of some local problems. Thank you for flagging that, @fcoveram. I fixed the logic of the collection page parameter validation, and now they do render on the server.
I've added the e2e tests, but didn't add visual regression tests to not make the tests run too long.

2023-12-05 10:42 UTC, fcoveram approved these changes
It looks great ✨🚀

2023-12-05 15:07 UTC, merged