Add correct label to exclude
WordPress/openverse pull request #3214
Opened 2023-10-17 13:21 UTC by ngken0995

## Fixes

Fixes #445  by @obulat 

## Description

Replace `project` with ` 🧭 project: thread, 🧭 project: proposal, 🧭 project: implementation plan` because there is a special board for the Projects and not in the backlog.

## Testing Instructions

## Checklist

- [X] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [X] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [N/S] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-10-17 17:02 UTC, stacimc approved these changes
LGTM! I'm not _100%_ sold on excluding `project: proposal` and `project: implementation plan` here as well 🤔 But I'm not opposed. I'll defer to other reviewers on that :)

2023-10-18 14:59 UTC, krysal requested changes
Thank you for you help, @ngken0995. Let's keep this as the issue says and limit the exclusion to project threads.

2023-10-18 14:59 UTC, krysal commented on .github/workflows/new_issues.yml
> +          labeled: "🧭 project: thread, 🧭 project: proposal, 🧭 project: implementation plan"
```suggestion
          labeled: "🧭 project: thread"
```

2023-10-18 14:59 UTC, krysal commented on .github/workflows/new_issues.yml
> +          labeled: "🧭 project: thread, 🧭 project: proposal, 🧭 project: implementation plan"
The proposals and implementations plans are issues that require PRs and reviews, so they shouldn't be ignored.

2023-10-20 03:35 UTC, obulat approved these changes
LGTM!

2023-10-24 03:38 UTC, merged