revise catalog quickstart
WordPress/openverse pull request #3325
Opened 2023-11-07 21:07 UTC by ngken0995

## Fixes

Fixes #2034 by @AetherUnbound 

## Description

- change the handbook url.
- move Web Crawl Data (retired) to a new location `documentation/general/retired.md`
- move `Catalog Deployments` from catalog to documentation.
- revise `just` with `just catalog/`
- revise Directory Structure

## Testing Instructions

## Checklist

- [X] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [X] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-11-07 22:10 UTC, AetherUnbound requested changes
Thank you for tackling this @ngken0995! I have a few suggested changes before we merge this 😄

2023-11-07 22:10 UTC, AetherUnbound commented on documentation/catalog/guides/quickstart.md
> -[DEPLOYMENT.md](https://github.com/WordPress/openverse/blob/main/catalog/DEPLOYMENT.md)
Since you've moved the deployment file to the documentation folder, `DEPLOYMENT.md` should also be removed from the repo!

2023-11-07 22:10 UTC, AetherUnbound commented on documentation/catalog/guides/quickstart.md
> +|   ├── *                                       # Documentation, configuration files, and project requirements
```suggestion
└── *                                       # Documentation, configuration files, and project requirements
```

2023-11-07 22:10 UTC, AetherUnbound commented on documentation/catalog/guides/quickstart.md
> +│   ├── templates/                          # Templates for generating new provider code
The spacing on the comments will need to be adjusted so it all aligns on the right, do you mind adjusting that?
![image](https://github.com/WordPress/openverse/assets/10214785/8e5f5fc0-d500-4f91-9ae6-a14dd19ed164)

2023-11-07 22:10 UTC, AetherUnbound commented on documentation/general/retired.md
I think this file might be better under `documentation/catalog/reference/retired.md`, do you mind moving it there instead?

2023-11-08 15:42 UTC, ngken0995 commented on documentation/catalog/guides/deployment.md
> +[`docker-compose.yml`](docker-compose.yml) is used to spin up Airflow in
I couldn't find `.docker/airflow` anywhere in the monorepo and replaced it with [catalog/dockerfile](https://github.com/WordPress/openverse/blob/main/catalog/Dockerfile).

2023-11-08 19:50 UTC, AetherUnbound approved these changes
Awesome, just one more note otherwise it's ready to go!

2023-11-08 19:50 UTC, AetherUnbound commented on documentation/catalog/guides/quickstart.md
> +|   ├── *                               # Documentation, configuration files, and project requirements
```suggestion
└── *                                   # Documentation, configuration files, and project requirements
```

2023-11-09 19:12 UTC, stacimc approved these changes
Fantastic 🚀

2023-11-09 19:12 UTC, merged