Adding IF-ELSE and Switch Case Curly Braces rules
WordPress/openverse pull request #3474
Opened 2023-12-06 07:36 UTC by bhavik001

Fixes #3386 by @dhruvkb

This PR incorporates changes to the ESLint configuration to enforce the use of braces in one-line if-else statements and case blocks inside switch statements. This update aims to enhance code readability and prevent potential issues in the future. The specific ESLint rules added are:

- Enabled ESLint's built-in curly rule.
- Enabled the unicorn plugin's switch-case-braces rule.

### Testing Instructions
1. Run ESLint on the project to check for adherence to the new rules: `pnpm run eslint`
2. If necessary, automatically fix fixable issues using: `pnpm run eslint --fix`

2023-12-06 10:12 UTC, obulat requested changes

2023-12-06 10:12 UTC, obulat commented on api/Pipfile.lock
Awesome start, @bhavik001. So many changes!
Could you revert the unrelated changes to the `Pipfile.lock` files?

2023-12-06 11:55 UTC, obulat approved these changes
I removed all of the unrelated changes (Pipfile.lock and pnpm lock file).
Thank you for your contribution, @bhavik001!

2023-12-06 23:12 UTC, sarayourfriend approved these changes
LGTM! Thanks for the quick follow up :pray:

2023-12-06 23:12 UTC, sarayourfriend commented on frontend/src/components/VAudioTrack/VAudioControl.vue
> +      } // to prevent focus
```suggestion
        // to prevent focus
        event.preventDefault()
      }
```

2023-12-06 23:12 UTC, sarayourfriend commented on frontend/src/components/VAudioTrack/VWaveform.vue
> +      } // to prevent focus
```suggestion
      if (!props.isTabbable) {
        // to prevent focus
        event.preventDefault()
      }
```

2023-12-07 04:54 UTC, dhruvkb approved these changes
Changes LGTM, thanks for the contribution @bhavik001 and thanks @obulat for pushing this over the finish line!

2023-12-07 04:54 UTC, dhruvkb commented on packages/eslint-plugin/src/configs/index.ts
> +    "unicorn/switch-case-braces": ["error"],
TIL about `unicorn` 🤦. This turned out to be quite straightforward.

2023-12-07 04:57 UTC, merged