Issue #3941 resolved
WordPress/openverse pull request #4037
Opened 2024-04-04 18:17 UTC by Collins-Webdev

Hi there,

I've made some enhancements to the code to address the issue described in #3941. Following the convention established, I updated references to audio works to use the phrase "audio track(s)" instead of just "audio".

Please review the changes and let me know if there are any further adjustments needed. Thank you for considering my contribution.

Best

2024-04-04 21:24 UTC, dhruvkb commented
Hi @Collins-Webdev, could you update your PR description to use the [pull request template](https://github.com/WordPress/openverse/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md)? If you have any questions please let us know in the comments.

2024-04-04 21:41 UTC, dhruvkb requested changes
The changes are good and you've made them in the exact right placc @Collins-Webdev! Thank you for the contributions.

However there are some grammatical issues that I have pointed out in the review. If you could please correct them that would be great. 

Let us know in the comments if you need any help. I will [convert this PR to a draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests) so that you can make the required changes and once you are done, you can [mark is as ready for review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review) again, thanks!

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +    description: "An extensive library of free stock photos, images, and audio track, available for free use.",
The word "track" was not needed here as we are referring to the entire body of audio works. Please revert.

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +        a: "{openverse} searches across more than 700 million images and audio track from open APIs and the {commonCrawl} dataset.",
We would use the plural form of the word here as we are referring to more than one audio track in this string.

```suggestion
        a: "{openverse} searches across more than 700 million images and audio tracks from open APIs and the {commonCrawl} dataset.",
```

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +        a: "Currently {openverse} only searches images and audio track, with search for video provided through External Sources.",
Please use the plural form.

```suggestion
        a: "Currently {openverse} only searches images and audio tracks, with search for video provided through External Sources.",
```

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +      audio: "Audio track Sources",
Please revert this change as "track" is not needed here. A source of audio tracks can be called an "audio source".

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +        countMore: "See over {localeCount} audio track found for {query}.",
Please use the plural form.
```suggestion
        count: "See {localeCount} audio tracks found for {query}.",
        countMore: "See over {localeCount} audio tracks found for {query}.",
```

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +      audio: "audio track",
Please use the plural form.
```suggestion
      audio: "audio tracks",
```

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +    relatedAudios: "Related audio track",
Please use the plural form.
```suggestion
    relatedAudios: "Related audio tracks",
```

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +      err_unsupported: "This audio track format is not supported by your browser.",
Please revert this change. The format used by the audio track is referred to as an "audio format".

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +    close: "Close the audio track player",
Please revert this change as "audio player" is the right word to refer to the player which plays an audio track.

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +          countMore: "Over {count} audio track files provided by this source",
The word "track" and "file" should not both be used as one removes the need for the other.

```suggestion
          zero: "No audio tracks provided by this source",
          count: "{count} audio track provided by this source|{count} audio tracks provided by this source",
          countMore: "Over {count} audio tracks provided by this source",
```

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +          countMore: "Over {count} audio track files with the selected tag",
Same note as above^. The use of "track(s)" will eliminate the need for the word "file(s)".

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +          countMore: "Over {count} audio track files by this creator.",
Same note as above^. The use of "track(s)" will eliminate the need for the word "file(s)".

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +    audio: "Audio track",
Please revert this change as we are referring to to the collection of all audio tracks so "Audio" is suitable here.

2024-04-04 21:41 UTC, dhruvkb commented on frontend/src/locales/scripts/en.json5
> +    seeAudio: "See all audio track",
Please use the plural form.
```suggestion
    seeAudio: "See all audio tracks",
```

2024-04-17 15:40 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +      title: "Audio track category",
```suggestion
      title: "Audio category",
```

2024-04-17 15:40 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +        zero: "No audio track found for {query}.",
```suggestion
        zero: "No audio tracks found for {query}.",
```

2024-04-17 15:43 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +    },
```suggestion
    },
```

2024-04-17 15:44 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +          count: "{count} audio track file by this creator.|{count} audio track files by this creator.",
```suggestion
          count: "{count} audio track by this creator.|{count} audio tracks by this creator.",
```

2024-04-17 15:44 UTC, obulat commented on frontend/src/locales/scripts/en.json5
>            zero: "No audio files by this creator.",
```suggestion
          zero: "No audio tracks by this creator.",
```

2024-04-17 15:44 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +          count: "{count} audio file provided by this source|{count} audio track files provided by this source",
```suggestion
          count: "{count} audio track provided by this source|{count} audio tracks provided by this source",
```

2024-04-17 15:45 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +          count: "{count} audio file with the selected tag|{count} audio track files with the selected tag",
```suggestion
          count: "{count} audio track with the selected tag|{count} audio tracks with the selected tag",
```

2024-04-19 22:47 UTC, Collins-Webdev commented
> Thank you for all your work on this, @Collins-Webdev ! I've added several more suggestions for changes. After adding them, could you mark this PR "Ready for review" so that we can approve and merge it?

Hello @obulat , 

It's a pleasure for me to be able to participate in such a large-scale project. I have taken your suggestions into account and made the necessary changes. Could you please review them and proceed with merging?
Thanks.

2024-04-20 03:29 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +  audioTrack: {
```suggestion
  audioTrack: {
```

2024-04-20 03:30 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +          count: "{count} audio track by this creator.|{count} audio tracks files by this creator.",
```suggestion
          count: "{count} audio track by this creator.|{count} audio tracks by this creator.",
```

2024-04-20 03:30 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +          count: "{count} audio track provided by this source|{count} audio tracks files provided by this source",
```suggestion
          count: "{count} audio track provided by this source|{count} audio tracks provided by this source",
```

2024-04-20 03:30 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +          count: "{count} audio track with the selected tag|{count} audio tracks files with the selected tag",
```suggestion
          count: "{count} audio track with the selected tag|{count} audio tracks with the selected tag",
```

2024-04-22 03:39 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +}
```suggestion
}

```

2024-04-22 05:32 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +     },
```suggestion
      },
```

2024-04-22 05:32 UTC, obulat commented on frontend/src/locales/scripts/en.json5
> +     },
Add missing space

2024-04-22 07:28 UTC, obulat requested changes
@Collins-Webdev, I added the whitespace changes to fix the linting step of the CI.

Now, the text of the `about` pages have changed, so we need to update the Visual regression testing snapshots. Here are instructions on how to do it: https://docs.openverse.org/frontend/guides/test.html#updating-snapshots

If you have any problems with this, please comment here - we can help or update for you.

2024-04-30 04:14 UTC, obulat approved these changes
I updated the failing snapshots, and the CI now passes.

Thank you for your contribution, @Collins-Webdev 🎉

2024-04-30 04:43 UTC, dhruvkb approved these changes
Thank you for the contribution @Collins-Webdev! Also thank you @obulat for making the pending changes.

2024-04-30 15:52 UTC, merged