Issue 2799: added instructions how to run ingestion script from command line
WordPress/openverse pull request #4083
Opened 2024-04-09 12:44 UTC by kuephi

## Fixes

Fixes #[issue number] by @[issue author]

## Description

## Testing Instructions

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2024-04-09 23:39 UTC, sarayourfriend approved these changes
LGTM! I am going to push two very small changes to align with our other "run this command" code blocks, but otherwise this is great. Thanks very much for the contribution @kuephi :pray:

2024-04-09 23:39 UTC, sarayourfriend commented on documentation/catalog/guides/adding_a_new_provider.md
> +  ```
```suggestion
  ```bash
```

2024-04-09 23:39 UTC, sarayourfriend commented on documentation/catalog/guides/adding_a_new_provider.md
> +  ```
```suggestion
  ```bash
```

2024-04-11 18:03 UTC, AetherUnbound requested changes
Thanks for the contribution @kuephi! Unfortunately, many of the catalog's provider scripts depend on Airflow and must be run from within the Docker stack. The issue (#2799) describes how this might be accomplished. Do you mind altering these instructions to direct users how to use the docker-related `just` commands instead? E.g. `just catalog/run bash` and then the python command needed to run the provider.

2024-04-12 11:59 UTC, kuephi commented
will have a look @AetherUnbound

2024-04-18 09:53 UTC, kuephi commented
changed it according to your comment. had to add a new command to the catalog rustfile too. Hope this will do it.

2024-04-18 23:47 UTC, AetherUnbound reviewed
Thanks for making the change, this looks great! I have one change requested around spelling. Also, it looks like linting is failing - would you be able to run `just lint` locally and address/commit the changes it's suggesting?

2024-04-18 23:47 UTC, AetherUnbound commented on documentation/catalog/guides/adding_a_new_provider.md
> +reciep. This will open a bash shell inside the docker stack of the catalog
Nit: spelling/punctuation
```suggestion
recipe. This will open a bash shell inside the docker stack of the catalog.
```

2024-04-19 15:44 UTC, AetherUnbound approved these changes
Thank you for the contribution! 😄

2024-04-19 15:44 UTC, merged