Fix the feature flags in production on hydration
WordPress/openverse pull request #4084
Opened 2024-04-09 18:08 UTC by obulat

## Fixes

Fixes #4082 by @obulat

## Description

The feature flag store was using the env variable to get the deployment environment and the flag state for this environment. However, the env variable is not available on the client. I moved the setting to `publicRuntimeConfig`. To use the config in the feature flag store functions (`getFlagStatus`, `getFeatureState`), I had to move them inside the store itself. Because `this` was not available in some getters that used these functions, I converted them to actions.

I also updated the e2e setup to only set the feature cookies when we explicitly set some feature state in `preparePageForTests`, otherwise we don't set it to not change the default state.

## Testing Instructions

On main, run the app in production mode using `just frontend/run build` and then `DEPLOYMENT_ENV=production just frontend/run start`.
Go to http://localhost:8443/preferences and open console. You should see the errors mentioned in the linked issue in the console. When you attempt to click on the switchable input, the inner circle disappears.

Do the same in this branch, and you should be able to change the state of the switchable flags without errors. You can check the cookie state to confirm the flag was set. You can also see that additional search views are visible when you turn them on.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like`Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2024-04-09 18:09 UTC, obulat commented on frontend/test/playwright/playwright.config.ts
> +      DEPLOYMENT_ENV: "staging",
```suggestion
```

2024-04-09 18:59 UTC, obulat commented on frontend/test/playwright/e2e/preferences.spec.ts
> +      expect(1).toEqual(9)
```suggestion
```

2024-04-09 23:49 UTC, sarayourfriend commented
~Unfortunately I don't see the error on `main` :frowning_face:. I've checked and made sure that I am on the latest commit on main, and don't see anything between d25fa3afa ("(tag: frontend-2024.04.09.03.50.12, tag: api-2024.04.09.03.50.11) Turn on additional search views frontend (#4043)") and HEAD that would influence this.~

~I've also tried enabling and disabling the feature, going back and forth between different pages, and I never get the error described in the issue.~

It turns out I didn't understand these instructions correctly:

> On main, run the app in production mode using just frontend/run build and then just frontend/run start.

I was just running the app using build and start, but did not pass `DEPLOYMENT_ENV=production` to the environment. I'll update the testing instructions to clarify this. I realised this after remembering the environment variable being involved in the code changes.

The error shows up for me now, so I'll get back to testing this.

2024-04-10 01:12 UTC, sarayourfriend approved these changes
This mostly LGTM. I was nervous about this change when I saw the line count, but in reviewing the code, I see that it is mostly moving things around, rather than actually making changes to the logic in any way.

As I mentioned private, I still think it is best _not_ to deploy new features to production in the second half of the week, and I did think this was our agreed approach (which is why we target Tuesdays for releases).

However, I am requesting changes, because one of the tests added in `prefereces.spec.ts` is incorrect. The requested change is either to (a) also fix the checkbox bug in this PR, (b) fix the checkbox bug in another PR that blocks this one, or (c) remove that test from this PR, fix the checkbox bug in a critical a11y PR, and in that PR add the test back.

The test as it stands should not be committed to main, though, no more than any other factually and logically incorrect test should.

2024-04-10 01:13 UTC, sarayourfriend requested changes
Sorry, I meant to request changes, no approve.

2024-04-10 01:24 UTC, sarayourfriend commented on frontend/test/playwright/e2e/preferences.spec.ts
> +      expect(inputCheckedStatus).toEqual(feature.checked ? "checked" : null)
Here's the issue for the checkbox bug: https://github.com/WordPress/openverse/iss

2024-04-10 04:59 UTC, obulat commented on frontend/test/playwright/e2e/preferences.spec.ts
> +      expect(inputCheckedStatus).toEqual(feature.checked ? "checked" : null)
Updated to use `isChecked` for semantic testing in [076043d](https://github.com/WordPress/openverse/pull/4084/commits/076043d0a00d2c3115b7848244b97ff0cbc73292)

2024-04-10 05:01 UTC, obulat commented on frontend/test/playwright/e2e/preferences.spec.ts
> +}
Updated in [670310f](https://github.com/WordPress/openverse/pull/4084/commits/670310fc66d588a7feee3bb77edd7da0f28b6f98)

2024-04-10 05:14 UTC, obulat commented on frontend/test/playwright/utils/navigation.ts
> +  cookies: Record<string, unknown>
Change reverted.
There was a type error when I made the `features` cookie optional. Fixed in 
[1b672a0](https://github.com/WordPress/openverse/pull/4084/commits/1b672a02470da4d0607f418eec34c0bfc7871052) by making the `cookiesToSet` to be of type `CookieMap`.

2024-04-11 15:38 UTC, dhruvkb approved these changes
LGTM, the changes work as expected locally. I am able to toggle all the preferences and see their effect in the app as well as in the cookies.

2024-04-12 15:15 UTC, zackkrida approved these changes
I think this looks good :+1: Looking forward to a future approach where we do not need to specify a list of feature flag values in frontend/test/playwright/utils/navigation.ts

2024-04-13 16:19 UTC, merged