Unify rollback & deployment, simplify deployment workflow
WordPress/openverse pull request #767
Opened 2023-02-23 23:25 UTC by AetherUnbound

## Fixes

Related to https://github.com/WordPress/openverse/issues/384

## Description

This PR incorporates the changes proposed in https://github.com/WordPress/openverse-infrastructure/pull/378 and unifies the rollback & deployment into a single action. It also simplifies the deployment workflow itself by templating which action to use based on the inputs. Lastly, it incorporates a fix that @dhruvkb identified in https://github.com/WordPress/openverse/pull/442 regarding the `image-tag` input to the CI/CD workflow.

## Testing Instructions

I _think_ we'll need to merge this to test it, but I'll see if I can launch the workflow from this branch as well prior to merging.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-02-25 20:05 UTC, dhruvkb requested changes
I like the changes but I have one note about the `-`/`_` in the API-NGINX image (and some nits about casing in the step names).

2023-02-25 20:05 UTC, dhruvkb commented on .github/actions/staging-api-deploy/action.yml
> +    - name: Validate `tag` input for django
```suggestion
    - name: Validate `tag` input for Django
```

2023-02-25 20:05 UTC, dhruvkb commented on .github/actions/staging-api-deploy/action.yml
> +        image: "ghcr.io/wordpress/openverse-api-nginx:${{ inputs.tag }}"
This was correct earlier. The image on GHCR: https://github.com/WordPress/openverse/pkgs/container/openverse-api_nginx

2023-02-25 20:05 UTC, dhruvkb commented on .github/actions/staging-nuxt-deploy/action.yml
> +    - name: Validate `tag` input for nuxt
```suggestion
    - name: Validate `tag` input for Nuxt
```

2023-02-27 13:29 UTC, obulat commented on .github/actions/staging-api-deploy/action.yml
> +              '`${{ inputs.tag }}` does not appear to be a valid tag for the ghcr.io/wordpress/openverse-api-nginx:latest image.'
Shouldn't the quotes change places: 
```suggestion
              `'${{ inputs.tag }}' does not appear to be a valid tag for the ghcr.io/wordpress/openverse-api-nginx:latest image.`
```

2023-02-27 18:45 UTC, AetherUnbound commented
Thanks for the eyes on this @dhruvkb and @obulat! All of the stuff y'all commented on are from auto-generated files, so I'll take your suggestions upstream to https://github.com/WordPress/openverse-infrastructure/pull/378 and apply them here as well 🙂

2023-02-27 22:44 UTC, AetherUnbound commented on .github/actions/staging-api-deploy/action.yml
> +                package_name: 'openverse-api-nginx',
Oh I didn't realize! Where/when was this changed? We'll have to update the infrastructure repo with this new image.

2023-02-27 22:45 UTC, AetherUnbound commented on .github/actions/staging-api-deploy/action.yml
> +                package_name: 'openverse-api-nginx',
Ah, found it here: https://github.com/WordPress/openverse/commit/9d4c9094d5f079a49cf78b9ecc646ba49c0e2654

2023-02-27 23:07 UTC, AetherUnbound commented on .github/actions/staging-api-deploy/action.yml
> +              '`${{ inputs.tag }}` does not appear to be a valid tag for the ghcr.io/wordpress/openverse-api-nginx:latest image.'
Gah, good catch!

2023-02-27 23:07 UTC, AetherUnbound commented on .github/actions/staging-api-deploy/action.yml
> +    - name: Validate `tag` input for nginx
Due to this being automatically generated, closest I could get was `Nginx` 😅 hope that's okay!

2023-02-27 23:12 UTC, zackkrida approved these changes
👍 I approved the PR which generates this file, so approving here as well.

2023-02-28 23:32 UTC, dhruvkb approved these changes
LGTM! Thanks for compensating for my ignorance and applying the changes at the right place.

2023-02-28 23:54 UTC, merged