Adding brand assets
WordPress/openverse pull request #888
Opened 2023-03-10 09:34 UTC by panchovm

## Description

Adding other brand assets for media uses in the `brand` folder.

## Assets added
These assets come from the following Design Library' sections.

![imagen](https://user-images.githubusercontent.com/895819/224279321-4ada399d-f9e5-4a0f-a5b5-36f227d1b407.png)

<img width="725" alt="CleanShot 2023-03-10 at 10 33 37@2x" src="https://user-images.githubusercontent.com/895819/224279383-08bf2e07-4614-4aad-9081-9a806bbf5bd2.png">

2023-03-10 12:10 UTC, obulat reviewed
Are these assets for use on the frontend or in documentation? If it is for the frontend, we should move it to `frontend/src/assets`.

2023-03-10 13:44 UTC, panchovm commented
Documentation. I saw a few people using old or wrong assets for social media or other non-frontend graphics.

2023-03-10 14:40 UTC, obulat approved these changes
Thank you for adding them!

2023-03-11 06:02 UTC, dhruvkb requested changes
@panchovm could you update the `README.md` file in the `brand/` directory with some guidelines on when to use which of these SVGs? To someone without that context, these SVGs seem pretty much the same and very easy to use the wrong one for the job.

2023-03-11 09:41 UTC, panchovm commented
I planned to do that, but PR seemed to work just for uploading the files. I might be wrong. If so, I definitely want to edit the `README.md` file.

2023-03-13 09:16 UTC, obulat commented on brand/README.md
> +![Openverse icon](wp-icon-openverse.svg)
```suggestion
![Openverse icon](wp-icon-openverse.svg)

```

2023-03-13 15:36 UTC, dhruvkb approved these changes
I still have no idea when to use which thumbnail 😅 but we can work on that separately. No need to block this PR over such a minor detail.

2023-03-13 15:55 UTC, zackkrida commented
@dhruvkb I've made a new issue for the discussion of branding guidelines: https://github.com/WordPress/openverse/issues/901

2023-03-13 15:55 UTC, merged