Prepare Docker setup for monorepo
WordPress/openverse pull request #889
Opened 2023-03-10 13:52 UTC by dhruvkb

## Fixes

Fixes #865 by @dhruvkb 
Fixes #866 by @dhruvkb

## Description

This PR updates the Docker setup for the API to make it modular, and more accommodating of the Docker setup of the catalog, when merged.

## Testing Instructions

CI should continue to pass as it an internal refactor.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-03-11 04:58 UTC, dhruvkb commented
@krysal fair point, I dropped all changes pertaining to #866 from this PR.

2023-03-13 18:32 UTC, dhruvkb commented
Upping priority to high as it blocked #866.

2023-03-14 21:06 UTC, AetherUnbound requested changes
This is fantastic! The code changes look good, but I can't build due to the following error:

```
j build
just dc build 
docker-compose -f docker-compose.yml build
unexpected character "-" in variable name near "http.cors.allow-origin=\"/.*/\"\n"
error: Recipe `dc` failed on line 117 with exit code 15
error: Recipe `build` failed on line 121 with exit code 15
```

I suspect this has something to do with the `docker/es/env.docker` file?

2023-03-14 22:00 UTC, dhruvkb commented
@AetherUnbound I cannot repro this locally. `just dc build` worked normally for me. What version of Compose are you using? Profiles are only supported by [Compose v2](https://docs.docker.com/compose/compose-v2/) (the Docker plugin) and not Compose v1 (the standalone tool).

2023-03-14 22:55 UTC, AetherUnbound commented
This is now running just fine on my desktop 🤨 You've got to be right, there's some weird version mismatch or something. Here's my desktop (working) report:

```
$ docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.8.13
OpenSSL version: OpenSSL 1.1.1q  5 Jul 2022
```

2023-03-14 23:01 UTC, AetherUnbound approved these changes
Confirmed that this works on my desktop! I'll post my laptop details once I'm on it again to see what might be the cause of the failure.

2023-03-14 23:28 UTC, AetherUnbound commented
Hmm, it's using `docker-compose` locally for me 🤔 
```

$ docker-compose version
Docker Compose version 2.15.0

$ docker compose version
Docker Compose version v2.16.0

$ which docker-compose
/home/linuxbrew/.linuxbrew/bin/docker-compose
```

I just ran `brew upgrade docker-compose` and now it's working! How odd! Sorry for the confusion 🙂

2023-03-15 19:16 UTC, krysal approved these changes
Very neat to have `justfile`s by services 💯

2023-03-15 19:16 UTC, krysal commented on load_sample_data.sh
> +}
Nice, this file is taking quite a good form.

2023-03-16 01:06 UTC, dhruvkb commented on sample_data/sample_audio.csv
Earlier we were populating `image_view` from sample data. Now we load `image` from sample data and refresh the matview. Same from audio.

2023-03-16 01:07 UTC, merged