Extract VCloseButton and add descriptive labels
WordPress/openverse pull request #988
Opened 2023-03-22 12:24 UTC by obulat

## Fixes

Fixes #618 by @sarayourfriend 
Fixes #609 by @sarayourfriend 

## Description

This PR extracts the close button into a new component, `VCloseButton`.

Some labels are updated to be more descriptive:
- Translation Banner: "Close the translation contribution help request banner"
- Migration Notice: "Close the announcement"
- Content settings menu on mobile: "Close the content settings menu"
- Internal header pages menu black modal: "Close the pages menu"

To make the buttons work well with the `focus-` custom Tailwind styles, I made it possible to remove the border from the filled VIconButton.

## Testing Instructions

Check the popovers (external sources, license explanation, report form), modals (mobile content settings, pages menu). The buttons should look and behave the same, but the name that you hear when using Screen reader should be more descriptive.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-03-23 14:58 UTC, obulat commented on frontend/src/components/VHeader/VHeaderMobile/VContentSettingsModalContent.vue
> +          class="self-center ms-auto"
```suggestion
          variant="filled-white"
          class="self-center ms-auto"
```

2023-04-05 04:00 UTC, dhruvkb requested changes
The `VCloseButton` component could benefit from stories and snapshots of those stories. It's a bit hard to picture the 5 variants based on solely names.

Also the fact that none of the existing stories changed is good (if it means that the button remains visually unchanged) or not-so-good (if is means that the button appears in none of them).

2023-04-05 04:14 UTC, obulat commented on frontend/src/components/VBanner/VNotificationBanner.vue
> +      type: String,
Wouldn't we have to update all the places that expect a string and we pass it a TranslateResult? 
I think that the Vue 3 version of `i18n` returns a string, so we will be able to just remove all of the `toString()`s from the codebase once we upgrade.

2023-04-05 05:48 UTC, obulat commented on frontend/src/components/VBanner/VNotificationBanner.vue
> +      type: String,
I didn't realize that your comment is only about this specific component, `VCloseButton`. I am going to update this :)

2023-04-05 09:59 UTC, obulat commented
> Also the fact that none of the existing stories changed is good (if it means that the button remains visually unchanged) or not-so-good (if is means that the button appears in none of them).

The buttons did not appear in stories, but they _did_ appear in other snapshots (External sources, global audio player, filter and header modals), and I had to tweak some things to make them pass. One such change was adding `focus-visible:` modifier to the `after:` element in the `focus` utilities. Without this change, even though the button on the global audio player did not have a border set,  it had a ring around it in resting state.

Great idea about stories! I've added them, but did not add tests. Do you think it's worth bloating the snapshots directory and making the tests longer, if we already have the snapshots in the components or pages VR tests, @dhruvkb ?

2023-04-05 13:04 UTC, dhruvkb approved these changes
Thanks for adding the story, it made the review so much easier thanks to the preview. As for the tests, if they're captured in other existing snapshots, I don't see any reason for duplicating them.

LGTM, except for a typo, but I won't block on it.

2023-04-05 13:04 UTC, dhruvkb commented on frontend/src/components/meta/VCloseButton.stories.mdx
> +    name="VCloseButton varuabts"
```suggestion
    name="VCloseButton variants"
```

2023-04-10 13:59 UTC, zackkrida approved these changes
@obulat in testing compared to production, I noticed the translation notification bar appears taller:

<img width="546" alt="CleanShot 2023-04-10 at 09 55 20@2x" src="https://user-images.githubusercontent.com/6351754/230915709-a8c786d6-8e40-44c5-8688-8f2b5bb5f585.png">
<img width="645" alt="CleanShot 2023-04-10 at 09 54 58@2x" src="https://user-images.githubusercontent.com/6351754/230915712-df91128b-c89a-4f98-8b8e-426d0afaad86.png">

However, this may be related to a production issue with Arabic in particular, as I'm seeing much more English here than locally:

https://openverse.org/ar

I believe the PR is correct though and this is some unrelated production issue.

2023-04-10 15:14 UTC, merged